from enum import Enum

class StoneColorCategory(str, Enum):
    """Enumerate the supported commercial stone colors."""
    PURE_WHITE = "Pure White"
    WARM_WHITE = "Warm White"
    OFF_WHITE = "Off White"
    IVORY = "Ivory"
    CREAM = "Cream"
    BEIGE = "Beige"
    SAND = "Sand"
    TAUPE = "Taupe"
    LIGHT_GREY = "Light Grey"
    GREY = "Grey"
    DARK_GREY = "Dark Grey"
    CHARCOAL = "Charcoal"
    BLACK = "Black"
    BROWN = "Brown"
    COFFEE_BROWN = "Coffee Brown"
    CHOCOLATE = "Chocolate"
    GREEN = "Green"
    EMERALD_GREEN = "Emerald Green"
    OLIVE = "Olive"
    BLUE_GREY = "Blue Grey"
    GOLD = "Gold"
    RUST = "Rust"
    PINK = "Pink"
    BURGUNDY = "Burgundy"
    RED = "Red"
    TERRACOTTA = "Terracotta"
    MULTI_COLOR = "Multi Color"
    MIXED_NEUTRAL = "Mixed Neutral"
